[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dotflow"
version = "0.1.0"
description = "A Python-based DOT language interpreter with multiple API styles"
authors = [
    {name = "Wambua", email = "swskye17@gmail.com"},
]
readme = "README.md"
license = {text = "MIT"}
keywords = ["graphviz", "dot", "diagram", "flowchart"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.8"
dependencies = []

[project.optional-dependencies]
dev = ["pytest", "black", "isort", "mypy"]
docs = ["sphinx", "sphinx-rtd-theme"]

[project.urls]
Homepage = "https://github.com/skye-cyber/dotflow"
Documentation = "https://dotflow.readthedocs.io"
Repository = "https://github.com/skye-cyber/dotflow"
"Bug Tracker" = "https://github.com/skye-cyber/dotflow/issues"

[project.scripts]
dotflow = "dotflow.cli.main:cli"
